export const PRIMARY_ACCOUNT_LIST_REQUEST = 'PRIMARY_ACCOUNT_LIST_REQUEST'
export const PRIMARY_ACCOUNT_LIST_SUCCESS = 'PRIMARY_ACCOUNT_LIST_SUCCESS'
export const PRIMARY_ACCOUNT_LIST_FAIL = 'PRIMARY_ACCOUNT_LIST_FAIL'