export const SAVINGS_ACCOUNT_LIST_REQUEST = 'SAVINGS_ACCOUNT_LIST_REQUEST'
export const SAVINGS_ACCOUNT_LIST_SUCCESS = 'SAVINGS_ACCOUNT_LIST_SUCCESS'
export const SAVINGS_ACCOUNT_LIST_FAIL = 'SAVINGS_ACCOUNT_LIST_FAIL'