export const TRANSACTION_DEPOSIT_REQUEST = 'TRANSACTION_DEPOSIT_REQUEST'
export const TRANSACTION_DEPOSIT_SUCCESS = 'TRANSACTION_DEPOSIT_SUCCESS'
export const TRANSACTION_DEPOSIT_FAIL = 'TRANSACTION_DEPOSIT_FAIL'
export const TRANSACTION_DEPOSIT_RESET = 'TRANSACTION_DEPOSIT_RESET'

export const TRANSACTION_WITHDRAWAL_REQUEST = 'TRANSACTION_WITHDRAW_REQUEST'
export const TRANSACTION_WITHDRAWAL_SUCCESS = 'TRANSACTION_WITHDRAW_SUCCESS'
export const TRANSACTION_WITHDRAWAL_FAIL = 'TRANSACTION_WITHDRAW_FAIL'
export const TRANSACTION_WITHDRAWAL_RESET = 'TRANSACTION_WITHDRAW_RESET'